# BlueMapSkinSupport configuration file
# ---
# verboseLogging
#     Enable this option if you want more detailed log output, which can be useful for diagnosing issues.
#     (Or if you're just curious how the plugin works!)
# ---
# alwaysUseSkinsRestorerForSkinLookup
# alwaysUseCustomSkinsManagerForSkinLookup
#     Enable these options if you want to *always* rely on SkinsRestorer / CustomSkinsManager to provide players' skins.
#     This will make it so that BlueMapSkinSupport will *never* use Mojang's native API to look up skins.
# ---
# prefsRevision
#     Please do not change this value, as it is used to track changes made to the configuration file format.

verboseLogging: false

alwaysUseSkinsRestorerForSkinLookup: false
alwaysUseCustomSkinsManagerForSkinLookup: false

prefsRevision: 2
