name: BlueMapSkinSupport
version: ${project.version}
description: Adds support to BlueMap for acquiring skins from custom skin provider plugins, as well as offline-mode servers.
load: POSTWORLD
author: Karen/あけみ (akemin_dayo)
website: https://github.com/akemin-dayo/BlueMapSkinSupport
main: ai.akemi.bluemapskinsupport.BlueMapSkinSupport
database: false
softdepend:
  - BlueMap
  - SkinsRestorer
  - CustomSkinsManager
