name: BlueMapOfflineSkinSupport
version: ${project.version}
description: Adds proper offline skin acquisition support to BlueMap's web UI.
load: POSTWORLD
author: Karen/あけみ
website: https://github.com/akemin-dayo/BlueMapOfflineSkinSupport
main: ai.akemi.bluemapofflineskinsupport.BlueMapOfflineSkinSupport
database: false
depend:
  - BlueMap
softdepend:
  - SkinsRestorer
  - CustomSkinsManager